import { useEffect, useMemo, useState } from 'react'

type Business = 'all' | 'lapas' | 'mercadinho'
type Page = 'inicio' | 'vendas' | 'estoque' | 'compras' | 'caixa' | 'fiado' | 'resultados' | 'config'
type Product = { id:number; business:'lapas'|'mercadinho'; name:string; category:string; unit:string; cost:number; price:number; stock:number; minStock:number; active:boolean }
type Sale = { id:number; business:'lapas'|'mercadinho'; productId:number; productName:string; quantity:number; total:number; payment:'PIX'|'Dinheiro'|'Cartão'|'Fiado'; date:string }
type Purchase = { id:number; business:'lapas'|'mercadinho'; productId:number; productName:string; quantity:number; total:number; supplier:string; date:string }
type Customer = { id:number; name:string; phone:string; balance:number }

const initialProducts:Product[] = [
{id:1,business:'lapas',name:'X-Burger',category:'Lanches',unit:'un',cost:7.2,price:18,stock:22,minStock:8,active:true},
{id:2,business:'lapas',name:'X-Salada',category:'Lanches',unit:'un',cost:8.1,price:20,stock:18,minStock:8,active:true},
{id:3,business:'lapas',name:'X-Bacon',category:'Lanches',unit:'un',cost:9.5,price:23,stock:14,minStock:6,active:true},
{id:4,business:'lapas',name:'X-Tudo',category:'Lanches',unit:'un',cost:12,price:29,stock:9,minStock:5,active:true},
{id:5,business:'lapas',name:'Batata Frita',category:'Porções',unit:'un',cost:4.2,price:12,stock:20,minStock:6,active:true},
{id:6,business:'lapas',name:'Refrigerante Lata',category:'Bebidas',unit:'un',cost:3.1,price:6,stock:30,minStock:10,active:true},
{id:101,business:'mercadinho',name:'Arroz 5 kg',category:'Alimentos',unit:'un',cost:24,price:31,stock:12,minStock:5,active:true},
{id:102,business:'mercadinho',name:'Feijão 1 kg',category:'Alimentos',unit:'un',cost:7.5,price:10.5,stock:7,minStock:5,active:true},
{id:103,business:'mercadinho',name:'Óleo 900 ml',category:'Alimentos',unit:'un',cost:5.2,price:7.5,stock:9,minStock:4,active:true},
{id:104,business:'mercadinho',name:'Açúcar 1 kg',category:'Alimentos',unit:'un',cost:4.2,price:6,stock:4,minStock:5,active:true},
{id:105,business:'mercadinho',name:'Detergente',category:'Limpeza',unit:'un',cost:1.8,price:3.5,stock:3,minStock:5,active:true},
{id:106,business:'mercadinho',name:'Refrigerante 2 L',category:'Bebidas',unit:'un',cost:6.5,price:10,stock:15,minStock:6,active:true}
]
const initialSales:Sale[] = [
{id:1,business:'lapas',productId:1,productName:'X-Burger',quantity:3,total:54,payment:'PIX',date:new Date().toISOString()},
{id:2,business:'lapas',productId:3,productName:'X-Bacon',quantity:2,total:46,payment:'Dinheiro',date:new Date().toISOString()},
{id:3,business:'mercadinho',productId:101,productName:'Arroz 5 kg',quantity:1,total:31,payment:'PIX',date:new Date().toISOString()}
]
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const today=()=>new Date().toLocaleDateString('pt-BR')
const save=<T,>(key:string,value:T)=>localStorage.setItem(key,JSON.stringify(value))
const load=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}

function App(){
const[page,setPage]=useState<Page>('inicio'),[business,setBusiness]=useState<Business>('all')
const[products,setProducts]=useState<Product[]>(()=>load('mn-products',initialProducts))
const[sales,setSales]=useState<Sale[]>(()=>load('mn-sales',initialSales))
const[purchases,setPurchases]=useState<Purchase[]>(()=>load('mn-purchases',[]))
const[customers,setCustomers]=useState<Customer[]>(()=>load('mn-customers',[{id:1,name:'Cliente exemplo',phone:'',balance:35}]))
const[toast,setToast]=useState(''),[search,setSearch]=useState('')
useEffect(()=>save('mn-products',products),[products]);useEffect(()=>save('mn-sales',sales),[sales]);useEffect(()=>save('mn-purchases',purchases),[purchases]);useEffect(()=>save('mn-customers',customers),[customers])
const visibleProducts=products.filter(p=>p.active&&(business==='all'||p.business===business))
const visibleSales=sales.filter(s=>business==='all'||s.business===business),visiblePurchases=purchases.filter(p=>business==='all'||p.business===business)
const revenue=visibleSales.reduce((a,s)=>a+s.total,0),purchaseTotal=visiblePurchases.reduce((a,p)=>a+p.total,0),lowStock=visibleProducts.filter(p=>p.stock<=p.minStock),openFiado=customers.reduce((a,c)=>a+c.balance,0)
const estimatedGross=visibleSales.reduce((sum,sale)=>{const p=products.find(x=>x.id===sale.productId);return sum+sale.quantity*((p?.price||0)-(p?.cost||0))},0)
const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(''),2800)}
const sell=(productId:number,quantity:number,payment:Sale['payment'])=>{const p=products.find(x=>x.id===productId);if(!p||quantity<=0)return;if(p.stock<quantity)return notify('Estoque insuficiente para essa venda.');setSales(v=>[{id:Date.now(),business:p.business,productId:p.id,productName:p.name,quantity,total:p.price*quantity,payment,date:new Date().toISOString()},...v]);setProducts(v=>v.map(x=>x.id===p.id?{...x,stock:x.stock-quantity}:x));notify('Venda registrada e estoque atualizado.')}
const addPurchase=(productId:number,quantity:number,supplier:string)=>{const p=products.find(x=>x.id===productId);if(!p||quantity<=0)return;setPurchases(v=>[{id:Date.now(),business:p.business,productId:p.id,productName:p.name,quantity,total:p.cost*quantity,supplier:supplier||'Fornecedor não informado',date:new Date().toISOString()},...v]);setProducts(v=>v.map(x=>x.id===p.id?{...x,stock:x.stock+quantity}:x));notify('Compra registrada e estoque atualizado.')}
const createWhatsApp=()=>{const list=products.filter(p=>p.business==='mercadinho'&&p.active&&p.stock>0).slice(0,30).map(p=>'• '+p.name+' — '+money(p.price)).join('%0A');const text='Olá! Quero fazer um pedido no Mercadinho da Família.%0A%0A'+list+'%0A%0AQuero saber a disponibilidade dos produtos e combinar a entrega/retirada.';window.open('https://wa.me/?text='+text,'_blank')}
const resetDemo=()=>{setProducts(initialProducts);setSales(initialSales);setPurchases([]);setCustomers([{id:1,name:'Cliente exemplo',phone:'',balance:35}]);notify('Dados de demonstração restaurados.')}
return <div className="app">
<header className="topbar"><div className="brand" onClick={()=>{setPage('inicio');setBusiness('all')}}><div className="brand-mark">MN</div><div><strong>Meu Negócio</strong><span>gestão simples, sem complicação</span></div></div><div className="top-actions"><span className="date-chip">Hoje, {today()}</span><select value={business} onChange={e=>setBusiness(e.target.value as Business)}><option value="all">Visão geral</option><option value="lapas">🍔 Lapas Burguer</option><option value="mercadinho">🛒 Mercadinho da Família</option></select></div></header>
<div className="layout"><aside className="sidebar">
<button className={page==='inicio'?'nav active':'nav'} onClick={()=>setPage('inicio')}>⌂ <span>Início</span></button><div className="nav-label">Operação</div>
<button className={page==='vendas'?'nav active':'nav'} onClick={()=>setPage('vendas')}>🧾 <span>Vendas</span></button>
<button className={page==='estoque'?'nav active':'nav'} onClick={()=>setPage('estoque')}>📦 <span>Estoque</span>{lowStock.length>0&&<b className="badge">{lowStock.length}</b>}</button>
<button className={page==='compras'?'nav active':'nav'} onClick={()=>setPage('compras')}>🚚 <span>Compras</span></button>
<button className={page==='caixa'?'nav active':'nav'} onClick={()=>setPage('caixa')}>💰 <span>Caixa</span></button>
<button className={page==='fiado'?'nav active':'nav'} onClick={()=>setPage('fiado')}>👤 <span>Fiado</span>{openFiado>0&&<b className="badge warn">!</b>}</button>
<div className="nav-label">Acompanhar</div><button className={page==='resultados'?'nav active':'nav'} onClick={()=>setPage('resultados')}>📊 <span>Meu resultado</span></button><button className={page==='config'?'nav active':'nav'} onClick={()=>setPage('config')}>⚙️ <span>Configurações</span></button>
<div className="sidebar-help"><strong>Precisa de ajuda?</strong><span>O sistema foi feito para você não precisar entender de contabilidade para saber como o negócio está.</span></div>
</aside><main className="main">
{page==='inicio'&&<Dashboard business={business} revenue={revenue} estimatedGross={estimatedGross} purchaseTotal={purchaseTotal} lowStock={lowStock} sales={visibleSales} products={visibleProducts} setPage={setPage} setBusiness={setBusiness} createWhatsApp={createWhatsApp}/>}
{page==='vendas'&&<SalesPage products={visibleProducts} business={business} onSell={sell} search={search} setSearch={setSearch} sales={visibleSales}/>}
{page==='estoque'&&<StockPage products={visibleProducts} search={search} setSearch={setSearch} onAdjust={(id,d)=>setProducts(v=>v.map(p=>p.id===id?{...p,stock:Math.max(0,p.stock+d)}:p))}/>}
{page==='compras'&&<PurchasesPage products={visibleProducts} purchases={visiblePurchases} onPurchase={addPurchase}/>}
{page==='caixa'&&<CashPage sales={visibleSales} purchases={visiblePurchases}/>}
{page==='fiado'&&<CreditPage customers={customers} setCustomers={setCustomers}/>}
{page==='resultados'&&<ResultsPage products={visibleProducts} sales={visibleSales} purchases={visiblePurchases}/>}
{page==='config'&&<SettingsPage onReset={resetDemo} createWhatsApp={createWhatsApp}/>}
</main></div>{toast&&<div className="toast">✓ {toast}</div>}</div>
}

function Dashboard({business,revenue,estimatedGross,purchaseTotal,lowStock,sales,products,setPage,setBusiness,createWhatsApp}:{business:Business;revenue:number;estimatedGross:number;purchaseTotal:number;lowStock:Product[];sales:Sale[];products:Product[];setPage:(p:Page)=>void;setBusiness:(b:Business)=>void;createWhatsApp:()=>void}){
const title=business==='lapas'?'Lapas Burguer':business==='mercadinho'?'Mercadinho da Família':'Visão geral'
return <div><div className="page-head"><div><span className="eyebrow">PAINEL DE HOJE</span><h1>{title}</h1><p>Veja rapidamente o que entrou, o que saiu e o que precisa da sua atenção.</p></div><div className="head-buttons"><button className="secondary" onClick={()=>setPage('vendas')}>+ Registrar venda</button><button className="primary" onClick={()=>setPage('estoque')}>Ver estoque</button></div></div>
{business==='all'&&<div className="business-cards"><button className="business-card lapas" onClick={()=>setBusiness('lapas')}><div className="business-icon">🍔</div><div><strong>LAPAS BURGUER</strong><span>Entrar na gestão dos lanches</span></div><b>→</b></button><button className="business-card market" onClick={()=>setBusiness('mercadinho')}><div className="business-icon">🛒</div><div><strong>MERCADINHO DA FAMÍLIA</strong><span>Entrar na gestão do mercadinho</span></div><b>→</b></button></div>}
<div className="metrics"><Metric label="Vendas registradas" value={money(revenue)} note="total vendido" icon="↗"/><Metric label="Compras" value={money(purchaseTotal)} note="saídas registradas" icon="↓"/><Metric label="Margem bruta estimada" value={money(estimatedGross)} note="antes das despesas" icon="◆"/><Metric label="Estoque baixo" value={String(lowStock.length)} note="itens para conferir" icon="!" danger={lowStock.length>0}/></div>
<div className="grid-2"><section className="card"><div className="card-head"><div><h2>Como está meu negócio?</h2><p>Um resumo sem linguagem complicada.</p></div><button className="link-btn" onClick={()=>setPage('resultados')}>Ver detalhes →</button></div><div className="simple-status"><div><span>💵 Quanto vendi?</span><strong>{money(revenue)}</strong></div><div><span>🚚 Quanto comprei?</span><strong>{money(purchaseTotal)}</strong></div><div><span>📦 O que está acabando?</span><strong>{lowStock.length?lowStock.length+' itens':'Nada urgente'}</strong></div><div><span>💰 O que sobrou das vendas?</span><strong>{money(estimatedGross)}</strong></div></div></section>
<section className="card"><div className="card-head"><div><h2>O que está me dando dinheiro?</h2><p>Custo, preço e diferença por produto.</p></div></div><div className="mini-list">{products.slice(0,5).map(p=><div className="mini-row" key={p.id}><span>{p.name}</span><strong>{money(p.price-p.cost)}</strong><small>por unidade</small></div>)}</div></section></div>
<div className="grid-2"><section className="card"><div className="card-head"><div><h2>Últimas vendas</h2><p>As movimentações mais recentes.</p></div><button className="link-btn" onClick={()=>setPage('vendas')}>Ver todas →</button></div><Table rows={sales.slice(0,6)}/></section>
<section className="card"><div className="card-head"><div><h2>Precisa comprar</h2><p>Itens abaixo do estoque mínimo.</p></div><button className="link-btn" onClick={()=>setPage('compras')}>Lista de compras →</button></div>{lowStock.length?<div className="alert-list">{lowStock.map(p=><div key={p.id}><span>⚠️ {p.name}</span><b>{p.stock} {p.unit}</b><small>mínimo {p.minStock}</small></div>)}</div>:<div className="empty">✓ Nenhum item abaixo do mínimo.</div>}</section></div>
{business!=='lapas'&&<section className="whatsapp-banner"><div><strong>📲 Pedidos pelo WhatsApp</strong><span>O Mercadinho pode enviar uma lista de produtos para o cliente iniciar o pedido.</span></div><button onClick={createWhatsApp}>Abrir pedido no WhatsApp</button></section>}</div>
}
function Metric({label,value,note,icon,danger}:{label:string;value:string;note:string;icon:string;danger?:boolean}){return <div className="metric"><div className={danger?'metric-icon danger':'metric-icon'}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}

function SalesPage({products,onSell,search,setSearch,sales}:{products:Product[];business:Business;onSell:(id:number,q:number,p:Sale['payment'])=>void;search:string;setSearch:(s:string)=>void;sales:Sale[]}){
const[selected,setSelected]=useState(products[0]?.id||0),[qty,setQty]=useState(1),[payment,setPayment]=useState<Sale['payment']>('PIX')
const filtered=products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase()))
useEffect(()=>{if(!filtered.some(p=>p.id===selected))setSelected(filtered[0]?.id||0)},[search])
const p=products.find(x=>x.id===selected)
return <div><div className="page-head"><div><span className="eyebrow">OPERAÇÃO</span><h1>Vendas</h1><p>Registre uma venda em poucos toques. O estoque é atualizado automaticamente.</p></div></div><div className="sale-layout"><section className="card sale-form"><h2>Registrar venda</h2><label>Produto<input placeholder="Buscar produto..." value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="product-picker">{filtered.slice(0,8).map(x=><button className={selected===x.id?'selected':''} key={x.id} onClick={()=>setSelected(x.id)}><span>{x.business==='lapas'?'🍔':'🛒'}</span><div><strong>{x.name}</strong><small>{money(x.price)} · estoque {x.stock}</small></div></button>)}</div><div className="form-grid"><label>Quantidade<input type="number" min="1" max={p?.stock||1} value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label>Pagamento<select value={payment} onChange={e=>setPayment(e.target.value as Sale['payment'])}><option>PIX</option><option>Dinheiro</option><option>Cartão</option><option>Fiado</option></select></label></div><div className="total-box"><span>Total da venda</span><strong>{money((p?.price||0)*qty)}</strong></div><button className="primary full" onClick={()=>{if(p){onSell(p.id,qty,payment);setQty(1)}}}>✓ Registrar venda</button></section><section className="card"><div className="card-head"><div><h2>Vendas recentes</h2><p>As movimentações registradas.</p></div></div><Table rows={sales.slice(0,15)}/></section></div></div>
}
function Table({rows}:{rows:Sale[]}){if(!rows.length)return <div className="empty">Nenhuma venda registrada ainda.</div>;return <div className="table-wrap"><table><thead><tr><th>Produto</th><th>Qtd.</th><th>Pagamento</th><th>Total</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.productName}</td><td>{r.quantity}</td><td><span className="pill">{r.payment}</span></td><td><strong>{money(r.total)}</strong></td></tr>)}</tbody></table></div>}

function StockPage({products,search,setSearch,onAdjust}:{products:Product[];search:string;setSearch:(s:string)=>void;onAdjust:(id:number,d:number)=>void}){const filtered=products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())||p.category.toLowerCase().includes(search.toLowerCase()));return <div><div className="page-head"><div><span className="eyebrow">OPERAÇÃO</span><h1>Estoque</h1><p>Saiba o que você tem, o que está acabando e ajuste pequenas diferenças.</p></div><button className="secondary">+ Cadastrar produto</button></div><div className="toolbar"><input placeholder="🔎  Procurar produto ou categoria..." value={search} onChange={e=>setSearch(e.target.value)}/><span>{filtered.length} produtos</span></div><section className="card table-card"><div className="table-wrap"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Custo</th><th>Venda</th><th>Estoque</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.business==='lapas'?'Lapas Burguer':'Mercadinho'}</small></td><td>{p.category}</td><td>{money(p.cost)}</td><td>{money(p.price)}</td><td><strong>{p.stock} {p.unit}</strong></td><td>{p.stock<=p.minStock?<span className="status danger">Comprar</span>:<span className="status ok">Normal</span>}</td><td><button className="tiny" onClick={()=>onAdjust(p.id,-1)}>−</button><button className="tiny" onClick={()=>onAdjust(p.id,1)}>+</button></td></tr>)}</tbody></table></div></section></div>}

function PurchasesPage({products,purchases,onPurchase}:{products:Product[];purchases:Purchase[];onPurchase:(id:number,q:number,s:string)=>void}){const[id,setId]=useState(products[0]?.id||0),[qty,setQty]=useState(1),[supplier,setSupplier]=useState('');return <div><div className="page-head"><div><span className="eyebrow">REPOSIÇÃO</span><h1>Compras</h1><p>Registre o que comprou. O sistema soma ao estoque e mostra a saída de dinheiro.</p></div></div><div className="grid-2"><section className="card"><h2>Registrar compra</h2><label>Produto<select value={id} onChange={e=>setId(Number(e.target.value))}>{products.map(p=><option key={p.id} value={p.id}>{p.name} — custo {money(p.cost)}</option>)}</select></label><div className="form-grid"><label>Quantidade<input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label>Fornecedor<input placeholder="Nome do fornecedor" value={supplier} onChange={e=>setSupplier(e.target.value)}/></label></div><div className="total-box"><span>Saída registrada</span><strong>{money((products.find(p=>p.id===id)?.cost||0)*qty)}</strong></div><button className="primary full" onClick={()=>{onPurchase(id,qty,supplier);setQty(1);setSupplier('')}}>✓ Registrar compra</button></section><section className="card"><div className="card-head"><div><h2>Lista de compras</h2><p>Itens abaixo do estoque mínimo.</p></div></div><div className="alert-list">{products.filter(p=>p.stock<=p.minStock).map(p=><div key={p.id}><span>⚠️ {p.name}</span><b>comprar {Math.max(1,p.minStock*2-p.stock)}</b><small>estoque atual: {p.stock}</small></div>)}</div></section></div><section className="card"><div className="card-head"><h2>Compras registradas</h2></div><div className="table-wrap"><table><thead><tr><th>Produto</th><th>Qtd.</th><th>Fornecedor</th><th>Total</th></tr></thead><tbody>{purchases.slice(0,15).map(p=><tr key={p.id}><td>{p.productName}</td><td>{p.quantity}</td><td>{p.supplier}</td><td>{money(p.total)}</td></tr>)}</tbody></table></div></section></div>}

function CashPage({sales,purchases}:{sales:Sale[];purchases:Purchase[]}){const payments=['PIX','Dinheiro','Cartão','Fiado'] as const;const inBy=payments.map(x=>({x,total:sales.filter(s=>s.payment===x).reduce((a,s)=>a+s.total,0)}));const totalIn=sales.reduce((a,s)=>a+s.total,0),totalOut=purchases.reduce((a,s)=>a+s.total,0);return <div><div className="page-head"><div><span className="eyebrow">DINHEIRO</span><h1>Caixa</h1><p>Veja quanto entrou, quanto saiu e o saldo das movimentações registradas.</p></div></div><div className="metrics"><Metric label="Entradas" value={money(totalIn)} note="vendas" icon="↗"/><Metric label="Saídas" value={money(totalOut)} note="compras registradas" icon="↓"/><Metric label="Saldo das movimentações" value={money(totalIn-totalOut)} note="antes de outras despesas" icon="="/></div><section className="card"><h2>Entradas por forma de pagamento</h2><div className="cash-list">{inBy.map(x=><div key={x.x}><span>{x.x}</span><strong>{money(x.total)}</strong><div className="bar"><i style={{width:totalIn?Math.min(100,x.total/totalIn*100)+'%':'0%'}}/></div></div>)}</div></section><div className="info-note">💡 <strong>Importante:</strong> faturamento não é a mesma coisa que lucro. O resultado real precisa considerar compras, despesas, perdas e outros custos.</div></div>}

function CreditPage({customers,setCustomers}:{customers:Customer[];setCustomers:(x:Customer[])=>void}){const[name,setName]=useState(''),[phone,setPhone]=useState('');const add=()=>{if(!name.trim())return;setCustomers([...customers,{id:Date.now(),name:name.trim(),phone,balance:0}]);setName('');setPhone('')};const pay=(id:number)=>setCustomers(customers.map(c=>c.id===id?{...c,balance:0}:c));return <div><div className="page-head"><div><span className="eyebrow">CLIENTES</span><h1>Fiado</h1><p>Controle quem está devendo sem precisar guardar tudo na cabeça.</p></div></div><div className="grid-2"><section className="card"><h2>Novo cliente</h2><label>Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do cliente"/></label><label>WhatsApp<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(00) 00000-0000"/></label><button className="primary full" onClick={add}>+ Cadastrar cliente</button></section><section className="card"><div className="card-head"><div><h2>Contas em aberto</h2><p>Total: {money(customers.reduce((a,c)=>a+c.balance,0))}</p></div></div><div className="customer-list">{customers.map(c=><div className="customer" key={c.id}><div><strong>{c.name}</strong><small>{c.phone||'Sem telefone'}</small></div><div><b>{money(c.balance)}</b>{c.balance>0&&<button className="tiny pay" onClick={()=>pay(c.id)}>Recebeu</button>}</div></div>)}</div></section></div></div>}

function ResultsPage({products,sales,purchases}:{products:Product[];sales:Sale[];purchases:Purchase[]}){const byProduct=products.map(p=>({p,total:sales.filter(s=>s.productId===p.id).reduce((a,s)=>a+s.quantity,0)})).filter(x=>x.total).sort((a,b)=>b.total-a.total);const revenue=sales.reduce((a,s)=>a+s.total,0),purchasesTotal=purchases.reduce((a,s)=>a+s.total,0);const gross=sales.reduce((a,s)=>a+s.quantity*((products.find(p=>p.id===s.productId)?.price||0)-(products.find(p=>p.id===s.productId)?.cost||0)),0);return <div><div className="page-head"><div><span className="eyebrow">VISÃO DO NEGÓCIO</span><h1>Meu resultado</h1><p>Os números que ajudam a entender se as vendas estão deixando dinheiro no negócio.</p></div></div><div className="result-hero"><div><span>Vendido</span><strong>{money(revenue)}</strong></div><div><span>Compras</span><strong>{money(purchasesTotal)}</strong></div><div><span>Margem bruta estimada</span><strong>{money(gross)}</strong></div></div><div className="grid-2"><section className="card"><h2>O que está me dando dinheiro?</h2><p className="muted">Margem estimada por unidade.</p><div className="profit-list">{products.slice().sort((a,b)=>(b.price-b.cost)-(a.price-a.cost)).slice(0,8).map(p=><div key={p.id}><span>{p.name}</span><b>{money(p.price-p.cost)}</b></div>)}</div></section><section className="card"><h2>Mais vendidos</h2><p className="muted">Quantidade registrada nas vendas.</p><div className="profit-list">{byProduct.slice(0,8).map(x=><div key={x.p.id}><span>{x.p.name}</span><b>{x.total} un.</b></div>)}</div></section></div><div className="info-note">📌 Este painel é uma estimativa de gestão. Para saber o lucro final, registre também despesas como aluguel, energia, taxas de cartão, entregas, salários e perdas.</div></div>}

function SettingsPage({onReset,createWhatsApp}:{onReset:()=>void;createWhatsApp:()=>void}){return <div><div className="page-head"><div><span className="eyebrow">SISTEMA</span><h1>Configurações</h1><p>Preferências e ferramentas de apoio.</p></div></div><div className="grid-2"><section className="card"><h2>Horário do Lapas Burguer</h2><div className="hours"><span>Segunda</span><b>Fechado</b><span>Terça a quinta</span><b>18h às 24h</b><span>Sexta e sábado</span><b>18h às 02h</b><span>Domingo</span><b>18h às 24h</b></div></section><section className="card"><h2>Mercadinho da Família</h2><p className="muted">Catálogo e pedidos pelo WhatsApp já fazem parte da estrutura.</p><button className="secondary full" onClick={createWhatsApp}>📲 Testar pedido pelo WhatsApp</button></section></div><section className="card danger-card"><h2>Dados de demonstração</h2><p>O protótipo guarda os dados neste navegador. Para uma operação real, vamos substituir isso por banco de dados e login.</p><button className="secondary" onClick={onReset}>Restaurar demonstração</button></section></div>}

export default App
